ACHIEVEMENTS = [
    {
        "key": "first_trade",
        "name": "First Trade",
        "description": "Complete your first buy or sell.",
        "difficulty": "easy",
        "metric": "trade_count",
        "operator": ">=",
        "target": 1,
    },
    {
        "key": "first_buy",
        "name": "First Buy",
        "description": "Buy stock for the first time.",
        "difficulty": "easy",
        "metric": "buy_count",
        "operator": ">=",
        "target": 1,
    },
    {
        "key": "first_sell",
        "name": "First Sell",
        "description": "Sell stock for the first time.",
        "difficulty": "easy",
        "metric": "sell_count",
        "operator": ">=",
        "target": 1,
    },
    {
        "key": "profile_writer",
        "name": "Profile Writer",
        "description": "Save a personal signature.",
        "difficulty": "easy",
        "metric": "has_bio",
        "operator": "truthy",
        "target": True,
    },
    {
        "key": "avatar_ready",
        "name": "Avatar Ready",
        "description": "Upload or generate an avatar.",
        "difficulty": "easy",
        "metric": "has_avatar",
        "operator": "truthy",
        "target": True,
    },
    {
        "key": "stock_holder",
        "name": "Stock Holder",
        "description": "Hold at least one stock.",
        "difficulty": "easy",
        "metric": "holding_count",
        "operator": ">=",
        "target": 1,
    },
    {
        "key": "active_trader",
        "name": "Active Trader",
        "description": "Complete 20 trades.",
        "difficulty": "medium",
        "metric": "trade_count",
        "operator": ">=",
        "target": 20,
    },
    {
        "key": "diversified_portfolio",
        "name": "Diversified Portfolio",
        "description": "Hold 3 different stocks at the same time.",
        "difficulty": "medium",
        "metric": "holding_count",
        "operator": ">=",
        "target": 3,
    },
    {
        "key": "first_profit",
        "name": "First Profit",
        "description": "Reach a positive total profit.",
        "difficulty": "medium",
        "metric": "total_profit",
        "operator": ">",
        "target": 0,
    },
    {
        "key": "top_10_trader",
        "name": "Top 10 Trader",
        "description": "Reach the top 10 by total assets.",
        "difficulty": "medium",
        "metric": "total_assets_rank",
        "operator": "<=",
        "target": 10,
    },
    {
        "key": "trading_master",
        "name": "Trading Master",
        "description": "Complete 100 trades.",
        "difficulty": "hard",
        "metric": "trade_count",
        "operator": ">=",
        "target": 100,
    },
    {
        "key": "market_champion",
        "name": "Market Champion",
        "description": "Reach rank 1 by total assets.",
        "difficulty": "hard",
        "metric": "total_assets_rank",
        "operator": "==",
        "target": 1,
    },
    {
        "key": "double_up",
        "name": "Double Up",
        "description": "Reach $20,000 total assets.",
        "difficulty": "hard",
        "metric": "total_assets",
        "operator": ">=",
        "target": 20000,
    },
    {
        "key": "market_collector",
        "name": "Market Collector",
        "description": "Hold every listed stock at the same time.",
        "difficulty": "hard",
        "metric": "holds_all_stocks",
        "operator": "truthy",
        "target": True,
    },
]
